

#' col2hex
#' 
#' Converts named colors to hex (html) codes.
#' 
#' @param color One or more named colors. Also acccepts hex colors (useful for
#'   adding alpha values).
#' @param alpha Alpha level ranging form 1.0 (opaque) to 0.0 (transparent). The 
#'   default (NULL) omits alpha columns from the returned hexidecimal 
#'   characters.
#' @return Hexidicimal color codes
#' @importFrom grDevices col2rgb
#' @export
col2hex <- function(color, alpha = NULL) {
  if (is.character(color)) {
    color <- col2rgb(color)
  }
  stopifnot(is.matrix(color))
  colors_and_matrices(color, alpha)
}

#' gg_cols
#'
#' @description Generates colors like those generated by
#'  '\pkg{ggplot2}.
#' @param n Number of colors (HEX values) to return.
#' @return Character vector of HEX color codes.
#'
#' @examples
#'
#' gg_cols(8)
#' @keywords internal
#' @importFrom grDevices hcl
#' @export
gg_cols <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}


#' @importFrom grDevices rgb col2rgb
alphacolor <- function(cols, a = .99) {
  cols <- t(col2rgb(cols, alpha = TRUE)) / 255
  rgb(cols, alpha = a)
}

#' @importFrom grDevices col2rgb
is.color <- function(x) {
  if (all(grepl("^#", x))) return(TRUE)
  x <- tryCatch(col2rgb(x),
                error = function(e) return(NULL))
  if (!is.null(x)) return(TRUE)
  FALSE
}

matrix2col <- function(f, x, alpha = NULL) {
  apply(x, 2, function(i) {
    args <- as.list(i)
    if (is.integer(i)) {
      args$maxColorValue <- 255
    } else {
      args$maxColorValue <- 1L
    }
    if (!is.null(alpha)) {
      args$alpha <- alpha * args$maxColorValue
    }
    do.call(f, as.list(args))
  })
}

colors_and_matrices <- function(color, alpha = NULL) {
  if (all(c("h", "s", "v") %in% row.names(color))) {
    color <- matrix2col("hsv", color, alpha)
  } else if (all(c("red", "green", "blue") %in% row.names(color))) {
    color <- matrix2col("rgb", color, alpha)
  }
  color
}
