#' Pipe operator
#'
#' @name %>%
#' @rdname pipe
#' @keywords internal
#' @export
#' @importFrom magrittr %>%
#' @usage lhs \%>\% rhs
NULL


#' tibble
#'
#' @name tbl_df
#' @rdname tbl_df
#' @keywords internal
#' @export
#' @importFrom dplyr tbl_df
#' @usage tbl_df(data.frame(x = rnorm(10), y = rnorm(10)))
NULL


#' tibble
#'
#' @name data_frame
#' @rdname data_frame
#' @keywords internal
#' @export
#' @importFrom dplyr data_frame
#' @usage data_frame(data.frame(x = rnorm(10), y = rnorm(10)))
NULL


#' gg_cols
#'
#' @description Generates colors like those generated by
#'  '\pkg{ggplot2}.
#' @param n Number of colors (HEX values) to return.
#' @return Character vector of HEX color codes.
#'
#' @examples
#'
#' gg_cols(8)
#' @keywords internal
#' @export
gg_cols <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
